./mtkang w preloader images/preloader_k65v1_64_bsp.bin 
./mtkang w cust images/cust.img
./mtkang w md1img images/md1img.img 
./mtkang w spmfw images/spmfw.img 
./mtkang w scp1 images/scp.img 
./mtkang w scp2 images/scp.img 
./mtkang w sspm_1 images/sspm.img 
./mtkang w sspm_2 images/sspm.img 
./mtkang w lk images/lk.img 
./mtkang w lk2 images/lk.img 
./mtkang w boot images/boot.img 
./mtkang w logo images/logo.bin 
./mtkang w dtbo images/dtbo.img 
./mtkang w tee1 images/tee.img 
./mtkang w tee2 images/tee.img 
./mtkang w super images/super.img 
./mtkang w cache images/cache.img 
./mtkang w userdata images/userdata.img
./mtk reset
