#!/bin/sh

if command -v mtkclient; then
mtkclient "$@"
exit
fi
if [ ! -d .venv ]; then
python -m venv .venv
.venv/bin/pip install -r mtkclient/requirements.txt
fi
.venv/bin/python mtkclient/mtk.py "$@"


